debug:
  datatype: mysql
  hostname: xueqiya.com:3306
  database: test
  username: root
  password: Xq10683766..

test:
  datatype: mysql
  hostname: xueqiya.com:3306
  database: test
  username: root
  password: Xq10683766..

release:
  datatype: mysql
  hostname: xueqiya.com:3306
  database: test
  username: root
  password: Xq10683766..